global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['10.0.24.123:9090','10.0.26.5':9100','10.0.19.31:9100']
