global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['10.0.20.71:9090','10.0.26.120':9100','10.0.28.229:9100']
